# Generated by Django 4.2.7 on 2024-05-02 01:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichiertelecharge',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
